logging:
  level:
    ROOT: info
    love.korni: info

server:
  config:
    category: DINAMIC (S)
    channel: Канал
    channelLivenessSec: 10

spring:
  jda:
    token: ${PASTE_YOUR_TOKEN_HERE}
    activity:
      type: DEFAULT
      activity: Mention me & type help